-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Users Table (Supabase Auth integration)
-- Note: Supabase handles auth.users, this is a public profile table if needed, 
-- but Tech Spec implies direct usage or mapping. 
-- We'll create a public.users table that references auth.users if we need to store app-specific data like membership_tier.
create table public.users (
  id uuid references auth.users on delete cascade not null primary key,
  email text, -- Copied from auth.users for easier querying
  role text check (role in ('USER', 'ADMIN')) default 'USER',
  membership_tier text check (membership_tier in ('FREE', 'PRO')) default 'FREE',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.users (id, email, role)
  values (new.id, new.email, 'USER');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Events Table
create table public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  target_date date not null, -- D-Day
  is_date_confirmed boolean default false,
  event_type text check (event_type in ('TYPE_A', 'TYPE_B')),
  hype_score int default 0,
  related_tickers text[], -- Array of ticker codes
  status text check (status in ('ACTIVE', 'FINISHED')) default 'ACTIVE',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Hype Metrics Table (Time-series)
create table public.hype_metrics (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) on delete cascade not null,
  recorded_at date not null default current_date,
  search_volume int default 0,
  community_buzz int default 0,
  youtube_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Event Proxies Table (Signals)
create table public.event_proxies (
  id bigint generated by default as identity primary key,
  parent_event_id bigint references public.events(id) on delete cascade not null,
  proxy_name text not null,
  detected_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for performance
create index idx_events_status on public.events(status);
create index idx_events_hype_score on public.events(hype_score desc);
create index idx_hype_metrics_event_id on public.hype_metrics(event_id);
create index idx_hype_metrics_recorded_at on public.hype_metrics(recorded_at);
